### PR TITLE
Integrate Airtable JavaScript SDK

### PR DESCRIPTION
**Pull request by vishwamartur**
Related to #52

Integrate the Airtable JavaScript SDK into the project.

* Add `airtable` to the `dependencies` section in `package.json`.
* Import `Airtable` from `airtable` in `src/app.module.ts` and add a new provider for `Airtable`.
* Create a new service class `AirtableService` in `src/app.service.airtable.ts` to interact with the Airtable API.
* Create a new controller class `AirtableController` in `src/app.controller.airtable.ts` to handle endpoints for Airtable API interactions.

## Release Notes

- **New Features**
  - Introduced support for Airtable database operations, including methods for creating, reading, updating, and deleting records.
  - Added new scripts for testing and seeding Airtable in the application.
  - Enhanced error handling and logging for database operations across various database types.
  
- **Improvements**
  - Improved batch processing for record creation with detailed error reporting.
  - Added schema validation for environment variables to ensure proper configuration.
  
- **Bug Fixes**
  - Fixed issues with logging and error handling in various database classes.
  
- **Documentation**
  - Updated documentation to reflect new features and changes in database interactions.

### CODE REVIEW

**Comment by andyslack** [comment]
Hi @vishwamartur 

Thank you so much for contributing to the project.

When adding new data sources, please follow this guide: https://llana.io/developers/adding-datasources

This ensures a consistent experience regardless of data source.

We should also look at setting up some tests (event if it's mock results) for the new data source.

Happy to jump on a call and discuss if easier.

**Comment by andyslack** [comment]
@vishwamartur 

Have a look at the guide and see how you get on, i'm away next week but can do code reviews etc... then if needed we can have a call the following week.

Happy coding and if you have any questions, just ask.

**Comment by andyslack** [comment]
Hi @vishwamartur 

Some nice improvements here; I still see that Airtable has its own controller; this should not be the case as all requests, regardless of data source, should come via the same endpoints. 

This allows users to switch data sources with only one `env` change, and no code refactor is needed.

Also, can we put the same demo database from the other data sources in your Airtable mockup so we have a real test dataset?

I'm excited to test this out :)

**Comment by vishwamartur** [comment]
Hi @andyslack,

Thanks for the feedback! I’m currently facing some issues and, unfortunately, won’t be able to fix this from my side. Could you please take on the task of updating the Airtable integration?

Let me know if there’s anything I can assist with. I appreciate your help!

**Comment by andyslack** [comment]
Sure, I'll take a look

**Comment by vishwamartur** [comment]
Could you please create a video or screen recording showing how you solve this issue? It would be really helpful for us.
@andyslack

**Pull request merged**
